plugin: aws_ec2
aws_profile: "{{ lookup('env', 'AWS_PROFILE') | default('default', true) }}"
regions:
  - eu-west-3
filters:
  tag:Name:
    - metabase_instance
    - airbyte_instance
  instance-state-name : running
hostnames:
  - instance-id
keyed_groups:
  - key: tags['Name']
    prefix: group
compose:
  ansible_host: instance_id
use_extra_vars: yes