plugin: aws_ec2
aws_profile: "{{ lookup('env', 'AWS_PROFILE') | default('default', true) }}"
# You can set a specific region to look for, it speeds up the inventory creation
#regions:
#  - eu-west-3
filters:
  tag:Name:
    - metabase-instance
    - airbyte-instance
  instance-state-name : running
hostnames:
  - instance-id
keyed_groups:
  - key: tags['Name']
    prefix: group
compose:
  ansible_host: instance_id
use_extra_vars: yes